experiment:
  name: "I3DBaseline"
  model_save_path: "./model" # path to save the trained model
  experiment_number: 0 # do not forget to change the experiment number

data:
  name: "DriveAndAct"
  util_location: "framework_activity_recognition.datautils.prepare_drivenact"
  split_nr: 101 # 1 2
  folder_splits: "./activities_3s/" # path to folder containing split ex: "./driveandact/iccv_activities_3s/activities_3s/"
  data_path: "./kinect_color/" # path to folder containing downsampled Drive&Act video data
  views: ["a_column_co_driver"]
  new_suffix: ".mp4"
  sampler:
    use: True
    location: "framework_activity_recognition.sampler.ImbalancedDatasetSampler"
    parameter: {}
  n_frame: 16 # 32 64
  frame_size: 224

student:
  location: "architecture.i3d.I3DLogit"
  modality: "rgb"
  dropout_prob: 0.5
  name: "inception"

pretraining:
  use: True
  path: "./model/pretrained/model_rgb.pth" # path to I3D model pretrained with Kinetics-400
  model_num_classes: 400
  fine_tune_only_last_layer: False
  last_layer_variable: "conv3d_0c_1x1"
  last_layer_class: "architecture.i3d.Unit3Dpy"
  last_layer_parameter: {"in_channels": 1024, "kernel_size": !!python/tuple [1, 1 ,1], "activation": null, "use_bias": True, "use_bn": False}

train:
  modality: "train_baseline"
  epoch: 200
  criterion: 
    name : "CrossEntropyLoss"
  optimizer:
    name: "SGD"
    parameter: {"lr": 0.05, "momentum": 0.9}
  batch_size: 2
  num_workers: 4
  scheduler:
    use: True
    name: "MultiStepLR"
    parameter: {"milestones": [70, 100,150,200,300,400,500,600,700], "gamma": 0.2}
  test_rate: 5

config:
  path: "./config/train/i3dbaseline.yaml"